name = "InteractiveViz"
uuid = "d14badfc-0adb-4d57-980e-37858d990fa5"
authors = ["Mandar Chitre <mandar@nus.edu.sg>"]
version = "0.6.0"

[deps]
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.6"
FillArrays = "1.0"
Makie = "0.19, 0.20"
GeometryBasics = "0.4"
Observables = "0.5"
Statistics = "1.9"
