name = "InteractiveViz"
uuid = "d14badfc-0adb-4d57-980e-37858d990fa5"
authors = ["Mandar Chitre <mandar@nus.edu.sg>"]
version = "0.1.1"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Colors = "0.11.2"
Makie = "0.9.6 - 0.11"
julia = "1.3"
